#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

test:
  path: /test
  controller: App\Controller\TestController::testMe
#main:
#  path: /
#  controller: App\Controller\UsuarioController::index